# Generated by Django 5.2 on 2025-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/users/default.jpg', null=True, upload_to='users/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
