# Generated by Django 5.1.4 on 2025-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
