# Generated by Django 5.1.4 on 2025-02-26 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequestmodel',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerequestmodel',
            name='sender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exchangerequestmodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='offered_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_skill', to='main.skillsmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='wanted_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_skill', to='main.skillsmodel'),
        ),
        migrations.AddField(
            model_name='exchangerequestmodel',
            name='receiver_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_skill', to='main.skillsmodel'),
        ),
        migrations.AddField(
            model_name='exchangerequestmodel',
            name='sender_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_sender', to='main.skillsmodel'),
        ),
        migrations.AddField(
            model_name='userskills',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.skillsmodel'),
        ),
        migrations.AddField(
            model_name='userskills',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
