# Generated by Django 5.2 on 2025-04-09 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='responder',
            field=models.ManyToManyField(null=True, related_name='responder', to=settings.AUTH_USER_MODEL),
        ),
    ]
