# Generated by Django 5.1.4 on 2025-02-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerequestmodel',
            options={'ordering': ['status'], 'verbose_name': 'Запрос обмена', 'verbose_name_plural': 'Запросы обмена'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['author'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='skillsmodel',
            options={'ordering': ['name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='userskills',
            options={'ordering': ['user'], 'verbose_name': 'Навык пользователя', 'verbose_name_plural': 'Навыки пользователей'},
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categorymodel'),
        ),
    ]
