# Generated by Django 5.2 on 2025-04-21 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postmodel_responder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequestmodel',
            name='reviewed_user',
            field=models.ManyToManyField(null=True, related_name='reviewed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchangerequestmodel',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Pending'), ('Принято', 'Accepted'), ('Отклонено', 'Declined'), ('Активно', 'Active'), ('Завершено', 'Completed')], default='Ожидание', max_length=10),
        ),
    ]
