# Generated by Django 5.2 on 2025-04-22 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_exchangerequestmodel_reviewed_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequestmodel',
            name='reviewed_user',
            field=models.ManyToManyField(blank=True, related_name='reviewed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='responder',
            field=models.ManyToManyField(blank=True, related_name='responder', to=settings.AUTH_USER_MODEL),
        ),
    ]
