# Generated by Django 5.1.4 on 2025-03-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequestmodel',
            name='receiver_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_skill', to='main.userskills'),
        ),
        migrations.AlterField(
            model_name='exchangerequestmodel',
            name='sender_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_sender', to='main.userskills'),
        ),
    ]
