# Generated by Django 5.1.4 on 2025-03-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_exchangerequestmodel_receiver_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='offered_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_skill', to='main.userskills'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='wanted_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_skill', to='main.userskills'),
        ),
    ]
