# Generated by Django 5.1.4 on 2025-03-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_postmodel_offered_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='wanted_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_skill', to='main.skillsmodel'),
        ),
    ]
